### ISSUE TITLE
IDM KEY should Unique and fix

### ISSUE THREAD

**Issue by KennethAduan** [256210KitsuuuuHiddenOnGitHub/resetKey30Days#1]
JABOL JABOL JABOL

**Comment by 256210KitsuuuuHiddenOnGitHub** [comment]
ack, creating a fix HAHHAHHAHHHA

**Comment by 256210KitsuuuuHiddenOnGitHub** [comment]
https://github.com/256210KitsuuuuHiddenOnGitHub/resetKey30Days/releases/tag/bored_p1

fixed
